version: "3.7"

services:
  timescale:
    image: timescale/timescaledb:latest-pg12
    container_name: timescale_av
    restart: unless-stopped
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=av
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=av
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/postgresql/data
  web:
    build: .
    command: uvicorn web.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "5002:80"
    depends_on:
      - timescale
    